#!/usr/bin/env python3
"""Regenerate the fixture guides from the real getting started page.

Each fixture is a copy of the page whose example document link points at an altered copy of the
tutorial's PDF, for rehearsing a failure or an envelope breach:

- getting-started-bad-premium.md: the bodily injury premium is $150 instead of $100. Expect the
  judge to fail it and the envelope to be outside (likely regression).
- getting-started-phone-format.md: the phone number reads (1800) 123-4567 instead of 1800 123 4567.
  Expect the judge to pass it and the envelope to be outside (behavior changed).

The altered PDFs are committed next to this script. Their links point at the branch in BRANCH,
because Sensible fetches documents by URL; repoint it after the branch merges.

Usage: python3 scripts/doc-detective/fixtures/build_fixtures.py
Run a fixture: scripts/doc-detective/run.sh scripts/doc-detective/fixtures/getting-started-bad-premium.md
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
PAGE = os.path.join(REPO_ROOT, "docs", "document extraction", "getting-started.md")
BRANCH = "doc-detective-getting-started-tests"
REAL_PDF = "https://raw.githubusercontent.com/sensible-hq/sensible-docs/v0/assets/pdfs/auto_insurance_anyco.pdf"
FIXTURE_URL = f"https://raw.githubusercontent.com/sensible-hq/sensible-docs/{BRANCH}/scripts/doc-detective/fixtures/"

FIXTURES = {
    "getting-started-bad-premium.md": ("auto_insurance_anyco_bad_premium.pdf",
                                       "the bodily injury premium is $150 instead of $100. Expect the judge to fail it and the envelope to be outside (likely regression)"),
    "getting-started-phone-format.md": ("auto_insurance_anyco_phone_format.pdf",
                                        "the customer service phone number is (1800) 123-4567 instead of 1800 123 4567. Expect the judge to pass it and the envelope to be outside (behavior changed)"),
}


def main():
    with open(PAGE, encoding="utf-8") as f:
        page = f.read()
    if page.count(REAL_PDF) != 1:
        raise SystemExit(f"Expected one link to {REAL_PDF} in {PAGE}")
    _, front_matter, body = page.split("---\n", 2)
    for name, (pdf, what) in FIXTURES.items():
        note = (f"<!-- Doc Detective test fixture, not published. Generated by build_fixtures.py from "
                f"docs/document extraction/getting-started.md: its example document link points at {pdf}, where {what}. -->\n")
        with open(os.path.join(HERE, name), "w", encoding="utf-8") as f:
            f.write("---\n" + front_matter + "---\n" + note + body.replace(REAL_PDF, FIXTURE_URL + pdf))
        print(f"Wrote {name}")


if __name__ == "__main__":
    main()
