name: Link checking lychee
on:
  push:
    branches:
      - main
    paths:
      - 'readme-sync/v0/**.md'
jobs:
  ci-health:
    name: "CI/Healthcare"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: update packages
        run: sudo apt update
      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # or your desired Python version

      - name: Install dependencies 🔧
        run: |
          cd ./scripts/check_links/
          pip install requests  
      - name: run download changelogs
        run: python ./scripts/check_links/download_changelogs.py
      - name: Link Checker for all md/mdx # https://github.com/marketplace/actions/lychee-broken-link-checker
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          fail: true
          args: --verbose --no-progress --exclude-all-private --exclude 'stackoverflow.com' --exclude 'https://api.sensible.so/v0/extract/layout_basics' --exclude 'https://platform.openai.com' --exclude 'support.discord.com' --exclude-path './node_modules' --exclude-path 'examples' --exclude-path 'docs/snippets/callouts.mdx' .