# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "html-proofer", "~> 3.19", :group => :test
gem 'html-pipeline'