name: Guide Link Checking
on:
  push:
    branches:
      - v0
    paths:
      - 'docs/**/*.md'
      - 'reference/**/*.md'
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'reference/**/*.md'
jobs:
  check-guide-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Set up Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install dependencies 🔧
        run: cd ./scripts/check_links/ && bundle install
      - name: Build HTML from markdown, check guide and reference links 🏗
        run: ruby ./scripts/check_links/check_links.rb
