name: Dev Sync markdown guides to ReadMe

# Run workflow for every push to the named dev branch branch
on:
  push:
    #name of your dev branch
    branches:
      - plg
    paths:
      - 'readme-sync/v0/**.md'

jobs:
  sync-guides:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        # using flowcommerce CLI rather than Readme's offical GH action for syncing b/c Readme's appears less powerful
      - name: clone readme-sync
        run: |
          git clone https://github.com/flowcommerce/readme-sync --branch v0.0.23 readme-cli-tool
      - name: install readme-sync
        run: |
           cd ./readme-cli-tool
           npm install

      - name: sync markdown guides (excludes changelog, API ref)
        # use new dev key that you get from a temp test project (remember you'll have to create the categories by hand in dash.readme and also create a v0 of docs in dash.readme)
        run: |
          npx ts-node ./readme-cli-tool/sync/index.mjs --apiKey ${{ secrets.DEV_README_KEY }} --version v1.0 --docs readme-sync/v0
