name: Linting style
on:
  push:
    branches: [ main ]
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vale
        uses: errata-ai/vale-action@master
        with:
          # Optional
          styles: |
            https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

          # Optional
          # config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

          # Optional
          files: __onlyModified #all
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    
        
 