# official is: https://github.com/errata-ai/vale-action

name: reviewdog
on:
  push:
    branches:
      - main
    #paths:
    # - 'readme-sync/v0/**.md'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: readme-sync/v0/**.md
