name: Style images

# Run workflow for every push to the `main` branch in dir assets
on:
  push:
    branches:
      - main
    paths:
      - 'readme-sync/assets/v0/images/screenshots/**'

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for writing images to the repo
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: update packages
        run: sudo apt update
      - name: Install ghostscript for ImageMagick
        run: sudo apt install ghostscript
      - name: Install ImageMagick
        run: sudo apt install -y imagemagick
      - name: run ImageMagick
        run: bash ./scripts/style_images.sh
      - name: auto commit changes from this workflow
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated image style commits"
