name: Sync markdown guides to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main
    paths:
      - 'readme-sync/v0/**.md'

jobs:
  sync-guides:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: clone readme-sync
        run: |
          git clone https://github.com/flowcommerce/readme-sync readme-cli-tool
      - name: install readme-sync
        run: |
           cd ./readme-cli-tool
           npm install

      - name: sync markdown guides (excludes changelog, API ref)
        run: |
          npx ts-node ./readme-cli-tool/sync/index.ts --apiKey ${{ secrets.README_API_KEY }} --version v0 --docs readme-sync/v0
