name: Sync OpenAPI definitions to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main
    paths:
      - '**.yml'
jobs:
  sync-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: Sync API definition 1 (extraction)
        # We recommend specifying a fixed version, i.e. @6.5.0
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@6.5.0
        with:
          # get the ID for the OAS file by importing the file manually in ReadMe Dash, clicking API definitions in the API ref
          # section of the dash, and copying the new ID. the file's title becomes the new category
          rdme: openapi openapi.yml --key=${{ secrets.README_API_KEY }} --id=6201a25efa760de40382e060
      - name: Sync API definition 2 (classification)
        uses: readmeio/rdme@6.5.0
        with:
          rdme: openapi openapi_classification.yml --key=${{ secrets.README_API_KEY }} --id=645bdc026d628e0026488c4e
